routes/web.php
<?php

use App\Http\Controllers\PersonController;
use App\Http\Controllers\ProductsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
    Auth::routes();
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('products', ProductsController::class)->middleware('auth');

Route::resource('person', PersonController::class)->middleware('auth');

app/Models/Person.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    use HasFactory;
    
    protected $table = 'person';

    protected $fillable = [
        'name',
        'cpf',
        'date_of_birth'
    ];

}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePersonRequest;
use App\Models\Person;
use Illuminate\Http\Request;

class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $person = Person::where([
            ['name', '!=', NULL],
            ['cpf', '!=', NULL],
            ['date_of_birth', '!=', NULL],
            [function ($query) use ($request) {
                if (($term = $request->term)) {
                    $query->orWhere('name', 'LIKE', '%' . $term . '%')->get();
                    $query->orWhere('cpf', 'LIKE', '%' . $term . '%')->get();
                    $query->orWhere('date_of_birth', 'LIKE', '%' . $term . '%')->get();
                }
            }]
        ])
        ->orderBy('id', 'desc')
        ->paginate(10);

        return view('person.index', compact('person'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('person.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePersonRequest $request)
    {
        Person::create($request->all());

        return redirect()->route('person.index')
            ->with('success', 'Pessoa criado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function show(Person $person)
    {
        return view('person.show', compact('person'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function edit(Person $person)
    {
        return view('person.edit', compact('person'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Person $person)
    {
        $request->validate([
            'name'=>'required',
            'cpf'=>'required',
            'date_of_birth'=>'required'
        ]);

        $person->update($request->all());

        return redirect()->route('person.index')
            ->with('success', 'Pessoa atualizada com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Person  $person
     * @return \Illuminate\Http\Response
     */
    public function destroy(Person $person)
    {
        $person->delete();

        return redirect()->route('person.index')
            ->with('success', 'Pessoa deletada com sucesso');
    }
}

resources/views/person/create.blade.php
@extends('layouts.app')


{{-- @push('scripts')
  <script>
    //Input mask
    $(document).ready(function($){
        $('.date').mask('00/00/0000');
        $('#cpf').mask('000.000.000-00', {reverse: true});
    });
  </script>
@endpush --}}

@section('content')

<div class="container">

    <div class="row">
        <div class="col-lg-12 margin-tb mb-3">
            <div class="float-left">
                <h2>Criar nova pessoa</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('person.index') }}" title="Voltar"> <i class="fas fa-backward "></i> Voltar </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Houve alguns problemas com sua entrada.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
      <div class="card-body">
        <form action="{{ route('person.store') }}" method="POST" >
            @csrf

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Nome:</strong>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Nome" required value="{{ old('name')}}">
                  </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                    <strong>CPF:</strong>
                    <input type="text" name="cpf" class="form-control @error('cpf') is-invalid @enderror" placeholder="CPF" id="cpf" required value="{{ old('cpf')}}" v-model="maskCpf" v-mask-cpf>
                  </div>
                </div>

              <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                  <strong>Data Nascimento:</strong>
                  <input type="date" name="date_of_birth" id="product" class="form-control @error('date_of_birth') is-invalid @enderror" placeholder="Data Nascimento" required value="{{ old('date_of_birth')}}">
                </div>
              </div>

              <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>

        </form>
      </div>
    </div>

</div>


@endsection

resources/views/person/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb mb-3">
            <div class="float-left">
                <h2>Editar pessoa</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('person.index') }}" title="Go back"> <i class="fas fa-backward "></i>  Voltar </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <form action="{{ route('person.update', $person->id) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nome:</strong>
                        <input type="text" name="name" value="{{ $person->name }}" class="form-control" placeholder="Nome">
                    </div>
                </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>CPF:</strong>
                            <input type="text" name="cpf" value="{{ $person->cpf }}" class="form-control" placeholder="CPF">
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Data Nascimento:</strong>
                            <input type="text" name="date_of_birth" class="form-control" placeholder="{{ $person->date_of_birth }}"
                                value="{{ $person->date_of_birth }}">
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

@endsection

resources/views/person/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <div class="row justify-content-center">
        <div class="col-lg-12 margin-tb mb-3">
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('person.create') }}" title="Criar produto"> <i class="fas fa-plus-circle"></i>
                    Criar </a>
            </div>
        </div>
    </div>
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div>
        <div class="mx-auto float-right mb-3">
            <form action="{{ route('person.index') }}" method="GET" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" name="term" placeholder="Buscar" id="term">
                    <div class="input-group-prepend">
                        <span class="input-group-btn">
                            <button class="btn btn-info" type="submit" title="Buscar">
                                <span class="fas fa-search"></span>
                            </button>
                        </span>
                    </div>
                    <div class="input-group-prepend">
                        <a href="{{ route('person.index') }}" class="">
                            <span class="input-group-btn">
                                <button class="btn btn-danger" type="button" title="Limpar busca">
                                    <span class="fas fa-sync-alt"></span>
                                </button>
                            </span>
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>cpf</th>
                    <th>Aniversario</th>
                    <th width="110px">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($person as $p)
                    <tr>
                        <td>{{ $p->name }}</td>
                        <td>{{ $p->cpf }}</td>
                        <td>{{ $p->date_of_birth }}</td>
                        <td>
                            <form action="{{ route('person.destroy', $p->id) }}" method="POST">

                                <a href="{{ route('person.show', $p->id) }}" title="show">
                                    <i class="fas fa-eye text-success  fa-lg"></i>
                                </a>

                                <a href="{{ route('person.edit', $p->id) }}">
                                    <i class="fas fa-edit  fa-lg"></i>
                                </a>

                                @csrf
                                @method('DELETE')

                                <button type="submit" title="delete" style="border: none; background-color:transparent;">
                                    <i class="fas fa-trash fa-lg text-danger"></i>

                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    
    <div class="pagination">
    {!! $person->links() !!}
    </div>
    
</div>


@endsection

resources/views/person/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>{{ $person->name }}</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('person.index') }}" title="Go back"> <i class="fas fa-backward "></i>  Voltar</a>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Nome:</strong>
                        {{ $person->name }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>CPF:</strong>
                        {{ $person->cpf }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Data Nascimento:</strong>
                        {{ $person->date_of_birth }}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Criado em:</strong>
                        {{ date_format($person->created_at, 'jS M Y') }}
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection